In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("Titanic_dataset.csv")

Saving Titanic_dataset.csv to Titanic_dataset.csv

In [ ]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

In [ ]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [ ]:
print("Missing Values:")
df.isnull().sum()

Missing Values:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
num_imputer = SimpleImputer(strategy='mean')

df[['Age', 'Fare']] = num_imputer.fit_transform(
    df[['Age', 'Fare']]
)

print("Numerical missing values handled")
df[['Age', 'Fare']].head()

Numerical missing values handled

    Age     Fare
0  34.5   7.8292
1  47.0   7.0000
2  62.0   9.6875
3  27.0   8.6625
4  22.0  12.2875

In [ ]:
cat_imputer = SimpleImputer(strategy='most_frequent')

df[['Embarked']] = cat_imputer.fit_transform(
    df[['Embarked']]
)

print("Categorical missing values handled")
df[['Embarked']].head()

Categorical missing values handled

  Embarked
0        Q
1        S
2        Q
3        S
4        S

In [ ]:
df.drop('Cabin', axis=1, inplace=True)

print("Cabin column removed")

Cabin column removed

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
categorical_columns = df.select_dtypes(include=['object']).columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['Name', 'Sex', 'Ticket', 'Embarked'], dtype='object')

In [ ]:
label_encoder = LabelEncoder()

df['Sex'] = label_encoder.fit_transform(df['Sex'])

df[['Sex']].head()

   Sex
0    1
1    0
2    1
3    1
4    0

In [ ]:
df = pd.get_dummies(df, columns=['Embarked'])

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,"Kelly, Mr. James",1,34.5,0,0,330911,7.8292,False,True,False
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",0,47.0,1,0,363272,7.0000,False,False,True
2,894,0,2,"Myles, Mr. Thomas Francis",1,62.0,0,0,240276,9.6875,False,True,False
3,895,0,3,"Wirz, Mr. Albert",1,27.0,0,0,315154,8.6625,False,False,True
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,22.0,1,1,3101298,12.2875,False,False,True

In [ ]:
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

print(numerical_columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare'],
      dtype='object')

In [ ]:
df[['Age', 'Fare']].head()

    Age     Fare
0  34.5   7.8292
1  47.0   7.0000
2  62.0   9.6875
3  27.0   8.6625
4  22.0  12.2875

In [ ]:
scaler = MinMaxScaler()

df[['Age', 'Fare']] = scaler.fit_transform(
    df[['Age', 'Fare']]
)

print("Scaling Completed")

Scaling Completed

In [ ]:
df[['Age', 'Fare']].head()

        Age      Fare
0  0.452723  0.015282
1  0.617566  0.013663
2  0.815377  0.018909
3  0.353818  0.016908
4  0.287881  0.023984

In [ ]:
X = df.drop(
    ['Survived', 'PassengerId', 'Name', 'Ticket'],
    axis=1
)

y = df['Survived']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)

print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

Training Features: (334, 9)
Testing Features: (84, 9)
Training Labels: (334,)
Testing Labels: (84,)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,"Kelly, Mr. James",1,0.452723,0,0,330911,0.015282,False,True,False
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",0,0.617566,1,0,363272,0.013663,False,False,True
2,894,0,2,"Myles, Mr. Thomas Francis",1,0.815377,0,0,240276,0.018909,False,True,False
3,895,0,3,"Wirz, Mr. Albert",1,0.353818,0,0,315154,0.016908,False,False,True
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0,0.287881,1,1,3101298,0.023984,False,False,True